### ISSUE TITLE
Container "api" complaining about Missing AI_API_URL environment variable

### ISSUE THREAD

**Issue by kyouch** [briefercloud/briefer#298]
I'm using Helm Chart to deploy in a Kubernetes cluster and  I've setup the `Values.ai.enabled` to be "false", consequently the portion of code below does not get created:
```
{{- if .Values.ai.enabled }}
            # AI related environment variables
            - name: AI_API_URL
              value: '{{ .Values.api.env.aiApiUrl }}'
            - name: AI_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: aiApiUsername
            - name: AI_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: aiApiPassword
            - name: PYTHON_ALLOWED_LIBRARIES
              value: '{{ .Values.api.env.pythonAllowedLibraries | default "pandas, plotly, matplotlib" }}'
{{- end }}
```
However, the container "api" is getting to CrashLoopBackOff" because the variable is missing, but well... I don't want to use the AI.
