### ISSUE TITLE
API port mapping issue when running app in Docker

### ISSUE THREAD

**Issue by offpepe** [briefercloud/briefer#5]
I am running the application using docker image and mapping the API port, but the web application continues to attempt to connect to port 8080, ignoring the mapped port.

![image](https://github.com/user-attachments/assets/58e5d6cc-a045-40f2-85ff-57469119c06c)

**Comment by vieiralucas** [comment]
Hello @offpepe, thank you for your issue.

If you pass an `API_URL` env variable to the container, it should fix your problem, in the example below I'm mapping to port `9090`

```bash
 docker run -d \
   -p 3000:3000 \
   -p 9090:8080 \
   -v briefer_psql_data:/var/lib/postgresql/data \
   -v briefer_jupyter_data:/home/jupyteruser \
   -v briefer_briefer_data:/home/briefer \
   --env API_URL="http://localhost:9090" \
   briefercloud/briefer
```

If that doesn't work, can you share the command you're running?
I can help you in a more synchronous way via our slack community channel btw.

**Comment by LuizBernardes** [comment]
> Hi @vieiralucas!
> 
> It works! I did hit a CORS issue so i had to add an extra env var to fix it, here's the command i ran:
> 
> ```shell
> docker run -d \  
>    -p 3999:3000 \
>    -p 8999:8080 \
>    -v briefer_psql_data:/var/lib/postgresql/data \
>    -v briefer_jupyter_data:/home/jupyteruser \
>    -v briefer_briefer_data:/home/briefer \
>    -e API_URL="http://localhost:8999" \
>    -e FRONTEND_URL="http://localhost:3999" \
>    briefercloud/briefer
> ```

I have a local environment with portainer and I put the following yaml
This is a physical machine with Ubuntu server
The web interface has a white screen and nothing appears
I tried using the machine's IP, localhost, 0.0.0.0 and 127.0.0.1

```
version: '3.8'

services:
  briefer:
    image: briefercloud/briefer
    ports:
      - "3999:3000"
      - "8999:8080"
    volumes:
      - briefer_psql_data:/var/lib/postgresql/data
      - briefer_jupyter_data:/home/jupyteruser
      - briefer_briefer_data:/home/briefer
    environment:
      - API_URL=192.168.15:8999
      - FRONTEND_URL=192.168.15:3999
      - ALLOW_HTTP=true

volumes:
  briefer_psql_data:
  briefer_jupyter_data:
  briefer_briefer_data:
```

![image](https://github.com/user-attachments/assets/4f887cc6-022d-4bd0-b728-9ac206a08bbb)
